# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20181102_0727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techer',
            new_name='Teacher',
        ),
    ]
