# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20181108_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='m_sStEmail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='m_sTeachEmail',
            field=models.CharField(max_length=50),
        ),
    ]
